networks:
  medianet:
    driver: bridge

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Karachi
    volumes:
      - ./config/prowlarr:/config
    ports:
      - 9696:9696
    networks:
      - medianet
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Karachi
    volumes:
      - ./config/sonarr:/config
      - ./data:/data
    ports:
      - 8989:8989
    networks:
      - medianet
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Karachi
    volumes:
      - ./config/radarr:/config
      - ./data:/data
    ports:
      - 7878:7878
    networks:
      - medianet
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Karachi
    volumes:
      - ./config/bazarr:/config
      - ./data/media:/data/media
    ports:
      - 6767:6767
    networks:
      - medianet
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Karachi
      - WEBUI_PORT=8080
    volumes:
      - ./config/qbit:/config
      - ./data/downloads:/data/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    networks:
      - medianet
    deploy:
      resources:
        limits:
          cpus: '1.5'        # max 1.5 CPU cores
          memory: 1G         # hard cap at 1GB RAM
        reservations:
          cpus: '0.25'
          memory: 256M
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Karachi
    volumes:
      - ./config/jellyfin:/config
      - ./data/media:/data/media
    ports:
      - 8096:8096
    networks:
      - medianet
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - TZ=Asia/Karachi
    volumes:
      - ./config/jellyseerr:/app/config
    ports:
      - 5055:5055
    networks:
      - medianet
    depends_on:
      - jellyfin
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - TZ=Asia/Karachi
    ports:
      - 8191:8191
    networks:
      - medianet
    restart: unless-stopped
